#include <nui/core.hpp>
#include <nui/window.hpp>

// This file is generated by nui.
#include <index.hpp>

int main()
{
    using namespace Nui;

    Window window{Nui::WindowOptions{
        .title = "Nui",
        .debug = true /* may open dev tools */,
    }};
    window.setSize(1920, 1080, WebViewHint::WEBVIEW_HINT_NONE);
    window.openDevTools();
    window.setHtml(index());
    window.run();
}